### ISSUE TITLE
Implement "drag and drop" strategy to upload files

### ISSUE THREAD

**Issue by Tubaleviao** [Tubaleviao/file-manager#3]
Create a div where we can drop files and them will be uploaded to server. The upload part can be made afterwards so just showing the files url's on console will be a good help already.

**Comment by i-aryan** [comment]
Hey, I'd like to work on it.

**Comment by shakti97** [comment]
Hey @Tubaleviao I would like to work on it

**Comment by Tubaleviao** [comment]
U just fixed this issue here: https://github.com/Tubaleviao/file-manager/commit/d429faa1bdc2eb5acf7ab839697232e15fb174d2
